package sharepoint

type SPList struct {
	Id                                        string                `json:"Id"`
	Title                                     string                `json:"Title"`
	CurrentChangeToken                        *ChangeToken          `json:"CurrentChangeToken"`
	BaseTemplate                              int                   `json:"BaseTemplate"`
	BaseType                                  int                   `json:"BaseType"`
	Created                                   string                `json:"Created"`
	ContentTypesEnabled                       bool                  `json:"ContentTypesEnabled"`
	AllowContentTypes                         bool                  `json:"AllowContentTypes"`
	CrawlNonDefaultViews                      bool                  `json:"CrawlNonDefaultViews"`
	CustomActionElements                      *CustomActionElements `json:"CustomActionElements"`
	DefaultContentApprovalWorkflowId          string                `json:"DefaultContentApprovalWorkflowId"`
	DefaultItemOpenUseListSetting             bool                  `json:"DefaultItemOpenUseListSetting"`
	Description                               string                `json:"Description"`
	Direction                                 string                `json:"Direction"`
	DisableGridEditing                        bool                  `json:"DisableGridEditing"`
	DocumentTemplateUrl                       string                `json:"DocumentTemplateUrl"`
	DraftVersionVisibility                    int                   `json:"DraftVersionVisibility"`
	EnableAttachments                         bool                  `json:"EnableAttachments"`
	EnableFolderCreation                      bool                  `json:"EnableFolderCreation"`
	EnableMinorVersions                       bool                  `json:"EnableMinorVersions"`
	EnableModeration                          bool                  `json:"EnableModeration"`
	EnableRequestSignOff                      bool                  `json:"EnableRequestSignOff"`
	EnableVersioning                          bool                  `json:"EnableVersioning"`
	EntityTypeName                            string                `json:"EntityTypeName"`
	ExemptFromBlockDownloadOfNonViewableFiles bool                  `json:"ExemptFromBlockDownloadOfNonViewableFiles"`
	FileSavePostProcessingEnabled             bool                  `json:"FileSavePostProcessingEnabled"`
	ForceCheckout                             bool                  `json:"ForceCheckout"`
	HasExternalDataSource                     bool                  `json:"HasExternalDataSource"`
	Hidden                                    bool                  `json:"Hidden"`
	ImagePath                                 *SPPath               `json:"ImagePath"`
	ImageUrl                                  string                `json:"ImageUrl"`
	IrmEnabled                                bool                  `json:"IrmEnabled"`
	IrmExpire                                 bool                  `json:"IrmExpire"`
	IrmReject                                 bool                  `json:"IrmReject"`
	IsApplicationList                         bool                  `json:"IsApplicationList"`
	IsCatalog                                 bool                  `json:"IsCatalog"`
	IsPrivate                                 bool                  `json:"IsPrivate"`
	ItemCount                                 int                   `json:"ItemCount"`
	LastItemDeletedDate                       string                `json:"LastItemDeletedDate"`
	LastItemModifiedDate                      string                `json:"LastItemModifiedDate"`
	LastItemUserModifiedDate                  string                `json:"LastItemUserModifiedDate"`
	ListExperienceOptions                     int                   `json:"ListExperienceOptions"`
	ListItemEntityTypeFullName                string                `json:"ListItemEntityTypeFullName"`
	MajorVersionLimit                         int                   `json:"MajorVersionLimit"`
	MajorWithMinorVersionsLimit               int                   `json:"MajorWithMinorVersionsLimit"`
	MultipleDataList                          bool                  `json:"MultipleDataList"`
	NoCrawl                                   bool                  `json:"NoCrawl"`
	ParentWebPath                             *SPPath               `json:"ParentWebPath"`
	ParentWebUrl                              string                `json:"ParentWebUrl"`
	ParserDisabled                            bool                  `json:"ParserDisabled"`
	ServerTemplateCanCreateFolders            bool                  `json:"ServerTemplateCanCreateFolders"`
	TemplateFeatureId                         string                `json:"TemplateFeatureId"`
	EditLink                                  string                `json:"odata.editLink"`
	ETag                                      string                `json:"odata.etag"`
	ODataId                                   string                `json:"odata.id"`
	ODataMetaData                             string                `json:"odata.metadata"`
	ODataType                                 string                `json:"odata.type"`
	MetaData                                  *MetaData             `json:"__metadata"`
}
